name: CI/CD Workflow for driver-did-abt

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Docker Build and Push
        uses: danubetech/github-action-docker-build-push@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_FILE: docker/Dockerfile
          CONTAINER_TAG: arcblock/driver-did-abt:latest
          # GITHUB_READ_PACKAGES_OWNER: Peiling Ding
          # GITHUB_READ_PACKAGES_TOKEN: ${{secrets.READ_PACKAGES_TOKEN}}